export const sagaActions = {
  REGISTER_USER: "REGISTER_USER",
  LOGIN_USER: "LOGIN_USER",
  USER_ONLINE: "USER_ONLINE",
  LOG_OUT: "LOG_OUT",
  USER_BY_ID: "USER_BY_ID",
  UPDATE_USER: "UPDATE_USER",
  UPDATE_AVATAR: "UPDATE_AVATAR",
  LOGOUT_USER: "LOGOUT_USER",
};
